exports.exportVisitorReport = (visitorData) => {
    console.log(visitorData);
    const cols = [
        { field: 'name', header: 'Product' },
        { field: 'model', header: 'Details' },
        { field: 'proposedQuantity', header: '#Proposed Qty' },
        // { field: 'approvedQuantity', header: '#Approved Qty' },
        { field: 'unitPrice', header: 'Unit Price' },
        // { field: 'buyingPrice', header: 'Buying Price' },
        { field: 'total', header: 'Total' },
    ]

    const exportColumns = cols.map(col => ({ title: col.header, dataKey: col.field }))

    const exportToPDF = () => {
        import('jspdf').then(jsPDF => {
            import('jspdf-autotable').then(() => {
                const doc = new jsPDF.default(0, 2)

                // Header
                doc.setFontSize(15)
                doc.setTextColor(10)
                doc.text(`Infozillion Teletech BD LTD.`, 102, 22)
                doc.setFontSize(12)
                doc.text(`Visitor Report`, 130, 32)

                doc.setFontSize(11)
                doc.text(`Report Month: ${visitorData?.reportMonth}`, 30, 45)
                doc.text(`Total visitors: ${visitorData?.visitorList.length}`, 30, 55)
                doc.text(`Generated by: ${visitorData?.generatedBy}`, 30, 45)
                doc.text(`Date: ${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, '0')}-${String(new Date().getDate()).padStart(2, '0')}`, 40, 55);

                doc.autoTable(exportColumns, visitorData?.visitorList.sort(), {
                    startY: 65,

                    didDrawPage: function (data) {

                        // Footer
                        var str = "Page " + doc.internal.getNumberOfPages();

                        doc.setFontSize(10);

                        // jsPDF 1.4+ uses getWidth, <1.4 uses .width
                        var pageSize = doc.internal.pageSize;
                        var pageHeight = pageSize.height
                            ? pageSize.height
                            : pageSize.getHeight();
                        doc.text(str, data.settings.margin.left, pageHeight - 10);
                    }
                });

                var pageSize = doc.internal.pageSize;
                var pageHeight = pageSize.height
                    ? pageSize.height
                    : pageSize.getHeight();

                var signatureLine = "__________________"
                var signature = visitorData.submittedBy;
                doc.text(signatureLine, 20, pageHeight - 40);
                // doc.text(signature, 40, pageHeight - 30);


                // doc.save(`Visitor Report - ${visitorData?.reportMonth}.pdf`)


            })
        })
    }

    exportToPDF();

}